-- Create users
INSERT INTO User (email, username, password_hash, bio) VALUES ("Hilario.Johnston44@gmail.com", "Bonita.Kiehn", "A1fsfXHiKk94dKo", "Non odio impedit quibusdam nemo pariatur. Est assumenda debitis enim amet illo rerum blanditiis omnis.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Sabina43@yahoo.com", "Julianne.Homenick", "d2GUwssTrOjOgJH", "Architecto in non expedita possimus quasi eos similique. Error vero est quae quae repudiandae consequuntur. Accusantium rem commodi neque iusto rerum ut temporibus ut et. Architecto qui recusandae ea magni. Quibusdam animi aut voluptatem sunt sit qui et excepturi minus. Dolore velit facere sequi non corporis nam repellat quisquam suscipit.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Wilford.Crona76@hotmail.com", "Reagan92", "sJaX1BZ0NaNGXk6", "Voluptatem et et maiores similique dolore eos et inventore. Eum deserunt consequatur aut. Natus laudantium doloribus inventore. Rem tenetur deleniti ex maiores nisi nostrum.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Dean65@hotmail.com", "Ryleigh68", "2c8Kz0JirXd0B2y", "Aut neque dolore aperiam possimus soluta debitis id. Praesentium ipsa eos. Atque culpa consequatur eaque molestias sapiente asperiores rem. Pariatur officia ducimus dolor ut. Sed alias beatae dignissimos id ipsum ut non explicabo. Iusto autem eum eius necessitatibus consequatur nobis.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Fritz.Torphy63@gmail.com", "Alta_Mills", "FrjnhmGRdbHUna3", "Quibusdam fugiat voluptatem est animi quam. Animi et enim. Odit incidunt voluptates incidunt cupiditate placeat provident velit incidunt molestiae. Corrupti dolore quasi enim et ullam nisi.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Leta_Kiehn74@hotmail.com", "Devante_Yundt93", "Ex4KA8HvrnaeOrk", "Repudiandae sint nobis voluptas accusantium. Quam eos enim est et ab inventore perspiciatis. Hic aut nulla ipsa nulla qui id. Debitis qui in illo rerum provident. Est dolore ipsa ullam dolorem.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Ulises_Lang47@hotmail.com", "Tressie_Murazik", "4uxOhBH_jiXdsdJ", "Provident vel veniam non. Rerum et aut quos velit perferendis. Et veritatis et tempora qui error.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Rosalinda.Kunde13@gmail.com", "Danielle_Yost", "3ZzdhH9Dm9P3qtT", "Qui et repudiandae consequatur omnis iusto. Enim est sunt hic culpa sint. Perferendis quibusdam rem qui illum nihil laborum beatae.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Roxanne.Lowe65@hotmail.com", "Raymond.Jaskolski82", "_gJhEYJ56BYvmUs", "Quia et voluptatem adipisci inventore. Dicta ipsa ipsam eveniet. Libero modi quia eum veniam ea.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Deven_Robel41@gmail.com", "Unique.Barton86", "uoQ59gqpcZyiQQW", "Repellat consequatur iste molestiae. Dignissimos rem illum at dignissimos perferendis doloremque doloremque voluptas. Eum quis fuga ratione optio. Aliquam aut laboriosam consequatur facilis provident atque culpa pariatur est. Quidem aliquam sed. Animi veritatis aspernatur autem et.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Foster58@gmail.com", "Lionel.Reynolds10", "MLVvxwwdWQ3xREx", "Corporis et doloremque ad et omnis minima ducimus ea perspiciatis. Veritatis quis et maxime aut aperiam. Est in quaerat et dolor. Enim ducimus optio esse qui beatae. Soluta sit id et aperiam expedita veniam. Molestiae perspiciatis recusandae earum eum accusamus vel voluptas.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Imelda18@hotmail.com", "Clay_Lowe", "UZIZ1gWruvT7Slt", "Libero et assumenda. Explicabo inventore non. Eum voluptatum nam deserunt alias et deleniti repudiandae ea et. Et velit officia velit quo perferendis est eaque officia. Qui et ut inventore ut et nihil fuga ipsa itaque.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Lesly.Predovic98@yahoo.com", "Rodrigo.Morar12", "14Xii93COsZsyF8", "Dolor aliquid atque qui eveniet quisquam eligendi quia voluptatem. Sit explicabo et sequi. Cumque et voluptates.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Layne_Nicolas@yahoo.com", "Seamus.Kuhn55", "IuYOLJmG3wHQOOs", "Deleniti rerum quia. Totam quidem dolores reiciendis nihil incidunt quisquam. Possimus inventore aut tenetur et facere.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Abigayle_Franecki@gmail.com", "Zetta95", "YnUF0UN7MAs4VS7", "Ut eius et exercitationem fugit. Est nihil est rerum provident totam qui numquam doloribus.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Octavia.Hilpert@yahoo.com", "Dortha40", "LxO8DCSk_7h0uZ8", "In temporibus ullam sit vel repellat et ut eaque sit. Quasi explicabo odio. Ea vero distinctio. Maiores explicabo aut et aut id.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Ova_Feeney@gmail.com", "Obie_Mohr", "nP3qbPHs3tJ7M71", "Velit eveniet enim molestiae nam repellendus praesentium quidem expedita. Ex odit expedita necessitatibus temporibus dolorem porro dolor quae odit. Aperiam dolorum optio et cupiditate. Autem ut distinctio consequatur consectetur quae explicabo commodi corrupti odio. Nulla non est ipsam.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Cayla.Jacobson87@yahoo.com", "Annalise_Murray", "vWuTbc0PhyrdG5l", "Facere eum ut aut. Enim quo temporibus placeat deserunt rem. Nam et adipisci dolor ut omnis velit. Eaque ipsa similique quis ea alias. Velit quae vel temporibus excepturi laborum repudiandae. Minima eum aut et necessitatibus ut at aperiam.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Celia.Goldner85@yahoo.com", "Kimberly.Beahan", "hJa2F_dLjNjXtaD", "Quos nulla cumque et ea. Quam maiores rerum.");
INSERT INTO User (email, username, password_hash, bio) VALUES ("Kristina.Deckow93@hotmail.com", "Gabriel61", "32KBX50EoiJgQ45", "Magni deserunt id labore asperiores. Soluta quae beatae commodi culpa doloremque impedit et eos maiores. Quae vel facere sit possimus.");

-- Create friendships
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (1, 14);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (1, 10);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (1, 12);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (1, 17);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (2, 12);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (2, 11);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (2, 10);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (2, 5);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (2, 3);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (3, 19);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (3, 18);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (3, 4);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (3, 16);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (3, 9);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (3, 6);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (4, 9);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (4, 3);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (4, 5);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (4, 18);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (4, 12);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (4, 19);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (5, 9);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (5, 10);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (5, 6);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (5, 11);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (5, 8);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (5, 16);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (6, 16);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (6, 15);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (6, 3);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (6, 19);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (6, 7);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (6, 5);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (7, 9);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (7, 11);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (7, 10);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (7, 12);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (7, 5);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (8, 10);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (8, 9);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (8, 2);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (8, 19);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (8, 1);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (8, 6);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (9, 4);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (9, 2);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (9, 6);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (9, 13);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (9, 12);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (10, 14);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (10, 6);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (10, 18);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (10, 8);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (11, 2);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (11, 8);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (11, 12);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (11, 3);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (11, 4);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (12, 14);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (12, 15);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (12, 16);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (12, 17);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (13, 17);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (13, 5);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (13, 7);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (13, 19);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (14, 2);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (14, 10);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (14, 9);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (14, 16);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (14, 18);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (15, 7);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (15, 2);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (15, 12);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (15, 3);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (15, 9);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (15, 13);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (16, 9);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (16, 1);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (16, 7);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (16, 18);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (16, 14);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (17, 15);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (17, 19);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (17, 11);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (17, 1);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (17, 3);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (17, 12);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (18, 14);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (18, 5);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (18, 9);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (18, 13);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (19, 13);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (19, 3);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (19, 6);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (20, 11);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (20, 16);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (20, 14);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (20, 12);
INSERT INTO Friendship (first_user_id, second_user_id) VALUES (20, 5);

-- Create friend requests
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (1, 4);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (1, 5);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (2, 13);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (3, 15);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (3, 13);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (4, 14);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (4, 13);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (5, 18);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (5, 14);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (6, 7);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (6, 19);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (7, 12);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (7, 16);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (8, 3);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (8, 17);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (9, 1);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (10, 11);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (10, 8);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (11, 5);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (11, 7);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (12, 3);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (12, 7);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (13, 11);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (13, 16);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (14, 16);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (14, 11);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (15, 14);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (15, 5);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (16, 19);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (16, 3);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (17, 9);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (17, 3);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (18, 4);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (19, 8);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (19, 14);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (20, 2);
INSERT INTO FriendRequest (from_user_id, to_user_id) VALUES (20, 6);

-- Create posts
INSERT INTO Post (post_body, author_id) VALUES ("Nihil cum et quibusdam.", 1);
INSERT INTO Post (post_body, author_id) VALUES ("Quae dolor fugiat magnam impedit amet totam nobis eos aut.", 1);
INSERT INTO Post (post_body, author_id) VALUES ("Tenetur est pariatur.", 1);
INSERT INTO Post (post_body, author_id) VALUES ("Est et hic natus autem.", 2);
INSERT INTO Post (post_body, author_id) VALUES ("Perferendis iste minima distinctio eos aut.", 2);
INSERT INTO Post (post_body, author_id) VALUES ("Asperiores dignissimos in amet illum expedita odio tenetur aperiam.", 2);
INSERT INTO Post (post_body, author_id) VALUES ("Incidunt sit ad vitae aliquam.", 3);
INSERT INTO Post (post_body, author_id) VALUES ("Voluptatem sed quisquam.", 3);
INSERT INTO Post (post_body, author_id) VALUES ("Quo dolores aut aut.", 3);
INSERT INTO Post (post_body, author_id) VALUES ("Suscipit soluta autem.", 4);
INSERT INTO Post (post_body, author_id) VALUES ("Quo quidem fugit.", 4);
INSERT INTO Post (post_body, author_id) VALUES ("Saepe dicta ea ex dicta.", 4);
INSERT INTO Post (post_body, author_id) VALUES ("Dolores et error voluptatem aspernatur et voluptatem est omnis.", 5);
INSERT INTO Post (post_body, author_id) VALUES ("Aut est quia et optio voluptatem autem.", 5);
INSERT INTO Post (post_body, author_id) VALUES ("Impedit et esse commodi fugit id molestiae.", 5);
INSERT INTO Post (post_body, author_id) VALUES ("Ut saepe deserunt saepe voluptatem.", 6);
INSERT INTO Post (post_body, author_id) VALUES ("Et et consequuntur sit tempore quia iste itaque.", 6);
INSERT INTO Post (post_body, author_id) VALUES ("Eos dolorem totam cumque.", 6);
INSERT INTO Post (post_body, author_id) VALUES ("Qui ut voluptas unde error enim autem quasi.", 7);
INSERT INTO Post (post_body, author_id) VALUES ("Esse ipsum reiciendis possimus natus et mollitia.", 7);
INSERT INTO Post (post_body, author_id) VALUES ("Incidunt sapiente odit saepe.", 7);
INSERT INTO Post (post_body, author_id) VALUES ("Rerum in nesciunt ratione.", 8);
INSERT INTO Post (post_body, author_id) VALUES ("Inventore doloribus voluptatum qui et.", 8);
INSERT INTO Post (post_body, author_id) VALUES ("Sint culpa aut in asperiores.", 8);
INSERT INTO Post (post_body, author_id) VALUES ("Ut quas et.", 9);
INSERT INTO Post (post_body, author_id) VALUES ("Laborum aut quidem alias nam repellat sapiente facere.", 9);
INSERT INTO Post (post_body, author_id) VALUES ("Consequatur optio at velit quis autem cumque consectetur.", 9);
INSERT INTO Post (post_body, author_id) VALUES ("Molestias officia id quia.", 10);
INSERT INTO Post (post_body, author_id) VALUES ("Architecto itaque qui.", 10);
INSERT INTO Post (post_body, author_id) VALUES ("Voluptate modi aut nisi tempora omnis voluptatum velit itaque.", 10);
INSERT INTO Post (post_body, author_id) VALUES ("Earum aspernatur eius dolores.", 11);
INSERT INTO Post (post_body, author_id) VALUES ("Quae at aut ea et nihil repellendus rerum.", 11);
INSERT INTO Post (post_body, author_id) VALUES ("Magni atque voluptates.", 11);
INSERT INTO Post (post_body, author_id) VALUES ("Ad laboriosam praesentium hic vel rerum.", 12);
INSERT INTO Post (post_body, author_id) VALUES ("Voluptas nobis eligendi officia dolorum placeat atque.", 12);
INSERT INTO Post (post_body, author_id) VALUES ("Minus dolore aliquam deserunt.", 12);
INSERT INTO Post (post_body, author_id) VALUES ("Laboriosam nulla sed placeat.", 13);
INSERT INTO Post (post_body, author_id) VALUES ("Quia illo dolorem corrupti possimus vero.", 13);
INSERT INTO Post (post_body, author_id) VALUES ("Enim nulla voluptatibus adipisci iure dignissimos at voluptatem.", 13);
INSERT INTO Post (post_body, author_id) VALUES ("Doloremque culpa architecto odio id animi nesciunt est sed.", 14);
INSERT INTO Post (post_body, author_id) VALUES ("Omnis nisi incidunt eveniet amet aut nulla quos aliquam.", 14);
INSERT INTO Post (post_body, author_id) VALUES ("Et voluptas mollitia numquam qui voluptatum ab natus aut.", 14);
INSERT INTO Post (post_body, author_id) VALUES ("Sunt labore sapiente vero aut ut debitis totam.", 15);
INSERT INTO Post (post_body, author_id) VALUES ("Consectetur laborum sunt.", 15);
INSERT INTO Post (post_body, author_id) VALUES ("Provident rerum rerum totam.", 15);
INSERT INTO Post (post_body, author_id) VALUES ("Architecto et deserunt dolorum vero.", 16);
INSERT INTO Post (post_body, author_id) VALUES ("Omnis ut qui.", 16);
INSERT INTO Post (post_body, author_id) VALUES ("Necessitatibus aut nemo non distinctio et nesciunt.", 16);
INSERT INTO Post (post_body, author_id) VALUES ("Sit ea sint repellendus quo voluptatibus.", 17);
INSERT INTO Post (post_body, author_id) VALUES ("Autem quos esse commodi quis sed veniam aut in illo.", 17);
INSERT INTO Post (post_body, author_id) VALUES ("Velit qui harum rem exercitationem labore eligendi veniam.", 17);
INSERT INTO Post (post_body, author_id) VALUES ("Ex eligendi velit earum omnis.", 18);
INSERT INTO Post (post_body, author_id) VALUES ("Quos facilis soluta fuga voluptas.", 18);
INSERT INTO Post (post_body, author_id) VALUES ("Consequuntur ut molestiae eos ipsam.", 18);
INSERT INTO Post (post_body, author_id) VALUES ("Aspernatur nesciunt consequatur asperiores.", 19);
INSERT INTO Post (post_body, author_id) VALUES ("Laboriosam non ipsam autem assumenda pariatur saepe ipsum.", 19);
INSERT INTO Post (post_body, author_id) VALUES ("Et aperiam doloribus corporis labore iure in.", 19);
INSERT INTO Post (post_body, author_id) VALUES ("Ipsa et error molestiae corrupti laborum.", 20);
INSERT INTO Post (post_body, author_id) VALUES ("Soluta vitae exercitationem deleniti iste quaerat possimus aut nisi.", 20);
INSERT INTO Post (post_body, author_id) VALUES ("Aliquid laborum sit sint occaecati impedit dolor.", 20);

-- Create post likes
INSERT INTO PostLike (post_id, user_id) VALUES (32, 1);
INSERT INTO PostLike (post_id, user_id) VALUES (33, 1);
INSERT INTO PostLike (post_id, user_id) VALUES (57, 1);
INSERT INTO PostLike (post_id, user_id) VALUES (6, 1);
INSERT INTO PostLike (post_id, user_id) VALUES (54, 1);
INSERT INTO PostLike (post_id, user_id) VALUES (25, 1);
INSERT INTO PostLike (post_id, user_id) VALUES (20, 2);
INSERT INTO PostLike (post_id, user_id) VALUES (43, 2);
INSERT INTO PostLike (post_id, user_id) VALUES (2, 2);
INSERT INTO PostLike (post_id, user_id) VALUES (35, 2);
INSERT INTO PostLike (post_id, user_id) VALUES (45, 2);
INSERT INTO PostLike (post_id, user_id) VALUES (27, 2);
INSERT INTO PostLike (post_id, user_id) VALUES (28, 3);
INSERT INTO PostLike (post_id, user_id) VALUES (45, 3);
INSERT INTO PostLike (post_id, user_id) VALUES (7, 3);
INSERT INTO PostLike (post_id, user_id) VALUES (32, 3);
INSERT INTO PostLike (post_id, user_id) VALUES (41, 3);
INSERT INTO PostLike (post_id, user_id) VALUES (37, 3);
INSERT INTO PostLike (post_id, user_id) VALUES (39, 4);
INSERT INTO PostLike (post_id, user_id) VALUES (45, 4);
INSERT INTO PostLike (post_id, user_id) VALUES (38, 4);
INSERT INTO PostLike (post_id, user_id) VALUES (21, 4);
INSERT INTO PostLike (post_id, user_id) VALUES (31, 4);
INSERT INTO PostLike (post_id, user_id) VALUES (48, 4);
INSERT INTO PostLike (post_id, user_id) VALUES (58, 5);
INSERT INTO PostLike (post_id, user_id) VALUES (47, 5);
INSERT INTO PostLike (post_id, user_id) VALUES (53, 5);
INSERT INTO PostLike (post_id, user_id) VALUES (30, 5);
INSERT INTO PostLike (post_id, user_id) VALUES (59, 5);
INSERT INTO PostLike (post_id, user_id) VALUES (41, 5);
INSERT INTO PostLike (post_id, user_id) VALUES (4, 6);
INSERT INTO PostLike (post_id, user_id) VALUES (47, 6);
INSERT INTO PostLike (post_id, user_id) VALUES (38, 6);
INSERT INTO PostLike (post_id, user_id) VALUES (9, 6);
INSERT INTO PostLike (post_id, user_id) VALUES (58, 6);
INSERT INTO PostLike (post_id, user_id) VALUES (40, 7);
INSERT INTO PostLike (post_id, user_id) VALUES (29, 7);
INSERT INTO PostLike (post_id, user_id) VALUES (17, 7);
INSERT INTO PostLike (post_id, user_id) VALUES (16, 7);
INSERT INTO PostLike (post_id, user_id) VALUES (33, 7);
INSERT INTO PostLike (post_id, user_id) VALUES (15, 8);
INSERT INTO PostLike (post_id, user_id) VALUES (43, 8);
INSERT INTO PostLike (post_id, user_id) VALUES (36, 8);
INSERT INTO PostLike (post_id, user_id) VALUES (59, 8);
INSERT INTO PostLike (post_id, user_id) VALUES (51, 8);
INSERT INTO PostLike (post_id, user_id) VALUES (18, 8);
INSERT INTO PostLike (post_id, user_id) VALUES (6, 9);
INSERT INTO PostLike (post_id, user_id) VALUES (4, 9);
INSERT INTO PostLike (post_id, user_id) VALUES (7, 9);
INSERT INTO PostLike (post_id, user_id) VALUES (45, 9);
INSERT INTO PostLike (post_id, user_id) VALUES (12, 9);
INSERT INTO PostLike (post_id, user_id) VALUES (46, 9);
INSERT INTO PostLike (post_id, user_id) VALUES (41, 10);
INSERT INTO PostLike (post_id, user_id) VALUES (31, 10);
INSERT INTO PostLike (post_id, user_id) VALUES (47, 10);
INSERT INTO PostLike (post_id, user_id) VALUES (26, 10);
INSERT INTO PostLike (post_id, user_id) VALUES (58, 10);
INSERT INTO PostLike (post_id, user_id) VALUES (40, 10);
INSERT INTO PostLike (post_id, user_id) VALUES (36, 11);
INSERT INTO PostLike (post_id, user_id) VALUES (51, 11);
INSERT INTO PostLike (post_id, user_id) VALUES (46, 11);
INSERT INTO PostLike (post_id, user_id) VALUES (18, 11);
INSERT INTO PostLike (post_id, user_id) VALUES (1, 11);
INSERT INTO PostLike (post_id, user_id) VALUES (31, 11);
INSERT INTO PostLike (post_id, user_id) VALUES (57, 12);
INSERT INTO PostLike (post_id, user_id) VALUES (10, 12);
INSERT INTO PostLike (post_id, user_id) VALUES (8, 12);
INSERT INTO PostLike (post_id, user_id) VALUES (32, 12);
INSERT INTO PostLike (post_id, user_id) VALUES (50, 12);
INSERT INTO PostLike (post_id, user_id) VALUES (18, 12);
INSERT INTO PostLike (post_id, user_id) VALUES (35, 13);
INSERT INTO PostLike (post_id, user_id) VALUES (34, 13);
INSERT INTO PostLike (post_id, user_id) VALUES (52, 13);
INSERT INTO PostLike (post_id, user_id) VALUES (46, 13);
INSERT INTO PostLike (post_id, user_id) VALUES (15, 13);
INSERT INTO PostLike (post_id, user_id) VALUES (34, 14);
INSERT INTO PostLike (post_id, user_id) VALUES (7, 14);
INSERT INTO PostLike (post_id, user_id) VALUES (52, 14);
INSERT INTO PostLike (post_id, user_id) VALUES (2, 14);
INSERT INTO PostLike (post_id, user_id) VALUES (46, 14);
INSERT INTO PostLike (post_id, user_id) VALUES (24, 14);
INSERT INTO PostLike (post_id, user_id) VALUES (48, 15);
INSERT INTO PostLike (post_id, user_id) VALUES (33, 15);
INSERT INTO PostLike (post_id, user_id) VALUES (23, 15);
INSERT INTO PostLike (post_id, user_id) VALUES (24, 15);
INSERT INTO PostLike (post_id, user_id) VALUES (17, 15);
INSERT INTO PostLike (post_id, user_id) VALUES (55, 15);
INSERT INTO PostLike (post_id, user_id) VALUES (45, 16);
INSERT INTO PostLike (post_id, user_id) VALUES (24, 16);
INSERT INTO PostLike (post_id, user_id) VALUES (27, 16);
INSERT INTO PostLike (post_id, user_id) VALUES (9, 16);
INSERT INTO PostLike (post_id, user_id) VALUES (41, 16);
INSERT INTO PostLike (post_id, user_id) VALUES (32, 17);
INSERT INTO PostLike (post_id, user_id) VALUES (53, 17);
INSERT INTO PostLike (post_id, user_id) VALUES (56, 17);
INSERT INTO PostLike (post_id, user_id) VALUES (4, 17);
INSERT INTO PostLike (post_id, user_id) VALUES (21, 17);
INSERT INTO PostLike (post_id, user_id) VALUES (29, 17);
INSERT INTO PostLike (post_id, user_id) VALUES (15, 18);
INSERT INTO PostLike (post_id, user_id) VALUES (14, 18);
INSERT INTO PostLike (post_id, user_id) VALUES (5, 18);
INSERT INTO PostLike (post_id, user_id) VALUES (45, 18);
INSERT INTO PostLike (post_id, user_id) VALUES (57, 18);
INSERT INTO PostLike (post_id, user_id) VALUES (29, 19);
INSERT INTO PostLike (post_id, user_id) VALUES (56, 19);
INSERT INTO PostLike (post_id, user_id) VALUES (8, 19);
INSERT INTO PostLike (post_id, user_id) VALUES (2, 19);
INSERT INTO PostLike (post_id, user_id) VALUES (41, 19);
INSERT INTO PostLike (post_id, user_id) VALUES (55, 19);
INSERT INTO PostLike (post_id, user_id) VALUES (33, 20);
INSERT INTO PostLike (post_id, user_id) VALUES (53, 20);
INSERT INTO PostLike (post_id, user_id) VALUES (51, 20);
INSERT INTO PostLike (post_id, user_id) VALUES (28, 20);
INSERT INTO PostLike (post_id, user_id) VALUES (9, 20);
INSERT INTO PostLike (post_id, user_id) VALUES (47, 20);

-- Create post comments
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Nisi voluptatem rerum.", 1, 18);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quam laboriosam dolor est maxime minima dolores aut sint perspiciatis.", 1, 10);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quia itaque necessitatibus aliquam id consequatur.", 2, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Dolor aut harum doloremque odit.", 2, 10);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Saepe ut mollitia omnis beatae omnis quis dignissimos dolor.", 3, 1);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Id labore ut quis adipisci qui omnis ut.", 3, 11);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quam omnis est alias et.", 4, 14);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Eos sit incidunt amet.", 4, 11);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Et eius facere laboriosam maiores impedit aut.", 5, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Neque pariatur eos dolor.", 5, 1);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Perferendis similique dolore et ut laboriosam iure a.", 6, 17);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Et et vel rem est consequatur rem.", 6, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Sapiente rerum nisi at nulla impedit neque.", 7, 5);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Et recusandae voluptatem molestiae.", 7, 3);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Reprehenderit eius dolor accusantium unde.", 8, 9);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Id sunt aut.", 8, 5);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quia dolorum corrupti.", 9, 16);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Impedit eaque est numquam itaque enim voluptas et ut reprehenderit.", 9, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Voluptas nemo consequatur suscipit ut voluptas enim.", 10, 13);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Consequatur maiores reprehenderit vel est velit dolor.", 10, 2);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Fugiat perferendis consequatur adipisci voluptas tempore totam voluptatem.", 11, 2);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ipsam omnis quis minus numquam ex est voluptatibus.", 11, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Dolorem est et quod recusandae est pariatur laboriosam.", 12, 13);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Mollitia tenetur consectetur quibusdam fuga.", 12, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Beatae vel reiciendis suscipit.", 13, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Veritatis reiciendis ratione.", 13, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Qui in saepe eos placeat excepturi nulla eum sed.", 14, 17);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Excepturi accusamus numquam ea iste.", 14, 14);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Omnis similique deleniti aut voluptatem explicabo porro molestiae.", 15, 9);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Neque doloremque nostrum et qui dolores autem eius numquam.", 15, 4);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Nemo deserunt nesciunt.", 16, 5);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Amet praesentium id et sit dolores nostrum et.", 16, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Recusandae facilis autem.", 17, 11);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quia iusto eaque dolor aliquam est et.", 17, 4);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ea vitae quod nobis perspiciatis eius sed voluptatem suscipit repellendus.", 18, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quisquam cum ipsa possimus dicta vero.", 18, 4);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Mollitia eveniet dolorem soluta nisi maiores alias et quidem quibusdam.", 19, 19);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("In mollitia reprehenderit commodi.", 19, 7);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quas voluptas et molestiae ullam non harum culpa nostrum.", 20, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Eaque ipsum aspernatur.", 20, 14);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Delectus qui ad autem ea et porro iure est.", 21, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ut minus expedita optio consequatur temporibus est totam.", 21, 18);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Vel voluptatibus delectus iusto minus incidunt aut sapiente ratione delectus.", 22, 2);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Consequatur eligendi sequi ut ut porro deserunt in aut.", 22, 14);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Vel et dolor molestias est facere porro reprehenderit est repellendus.", 23, 11);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Consequuntur omnis numquam et voluptate minima at blanditiis.", 23, 4);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Sit voluptas quos facilis ut non.", 24, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Omnis debitis quae optio similique vel eligendi.", 24, 18);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Rerum voluptas in.", 25, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ipsa odio quis.", 25, 16);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Et sit quia sed eos.", 26, 19);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Suscipit adipisci veniam ratione ea aliquid recusandae et.", 26, 3);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Sapiente nihil placeat optio veritatis quia repudiandae aut officiis nihil.", 27, 13);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Tempore non eum non voluptatem doloribus odio odit.", 27, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Sint molestiae minima possimus ipsa voluptatibus occaecati quia.", 28, 7);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Enim est omnis modi id natus architecto rerum quos id.", 28, 2);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Rerum voluptatem rerum repudiandae saepe et.", 29, 6);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ullam explicabo ut sunt.", 29, 4);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quibusdam ut quasi aperiam laborum totam id harum impedit.", 30, 4);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Voluptas animi magnam eaque voluptas alias esse.", 30, 1);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ipsum minus perferendis similique eos repellat et.", 31, 7);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Eos labore aut unde unde.", 31, 11);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Voluptatem nihil quia voluptatibus.", 32, 6);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Et velit et pariatur aut quis laborum.", 32, 4);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Accusamus laudantium aut fugit accusantium qui occaecati quis non debitis.", 33, 13);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Accusantium debitis incidunt non alias accusamus.", 33, 14);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Nobis at aut at.", 34, 10);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Maiores libero quos maiores laboriosam molestias dolores animi nisi quia.", 34, 16);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Consequatur consequuntur reprehenderit.", 35, 17);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Qui et reprehenderit similique.", 35, 16);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Fugiat et nihil quod sapiente sed.", 36, 4);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Et et omnis et aperiam animi nihil dolore.", 36, 10);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ut consequatur sed rem.", 37, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ut aut praesentium mollitia ut beatae.", 37, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quos et id accusamus rerum molestiae sit.", 38, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Vero culpa officia sit molestiae ut quod.", 38, 2);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Et sequi quas.", 39, 16);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ullam delectus vero.", 39, 9);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Sint quos aut quos velit harum sunt consequuntur aliquam.", 40, 3);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Voluptatem non soluta ut sunt et aut accusamus hic ut.", 40, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Provident iure ut quo voluptatem.", 41, 1);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quia repellendus quisquam dolorem libero nisi.", 41, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quae dolor mollitia dolorem sint nisi sit sunt consequuntur.", 42, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Quidem ratione sunt eveniet reiciendis facere.", 42, 9);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Necessitatibus placeat enim laudantium fugiat eveniet pariatur.", 43, 10);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Sunt recusandae eius sit hic sed.", 43, 14);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Qui est consequatur occaecati illo.", 44, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Hic velit voluptatem.", 44, 6);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Velit qui eaque amet praesentium modi ut.", 45, 14);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Aut odio vero.", 45, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ut magnam at et qui numquam.", 46, 18);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ipsam est doloribus.", 46, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Sint facere illo.", 47, 17);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Optio a maxime voluptatem et voluptatibus sequi vel rerum.", 47, 10);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Expedita explicabo aliquid ex quasi quia amet.", 48, 18);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Cum ut vel dolores delectus et reprehenderit perspiciatis et architecto.", 48, 11);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Facilis deleniti voluptate blanditiis magnam consequuntur.", 49, 11);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Est sunt quo nulla.", 49, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Ut ratione est blanditiis cum doloremque tenetur esse et eos.", 50, 1);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Sit consequatur voluptates recusandae earum.", 50, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Aut ducimus sit qui harum eum ut praesentium sint quis.", 51, 3);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Autem fugiat error libero assumenda aut asperiores.", 51, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Illum animi est distinctio enim eum natus quasi.", 52, 1);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Magnam et id dolorem molestiae facere.", 52, 3);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Dolor dolore voluptatibus.", 53, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Perferendis itaque asperiores laborum voluptate aperiam quo quis.", 53, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Laudantium enim ut quia tempore commodi repellendus nesciunt.", 54, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Dolor hic odit error quo quia deleniti eius quos aspernatur.", 54, 13);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Aut unde autem et voluptatem.", 55, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Sunt ut et voluptatem quisquam dolorem ratione.", 55, 7);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Dolor aut id eveniet.", 56, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Vero eaque commodi accusamus eius ea mollitia nulla non.", 56, 8);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Est minima voluptatum et.", 57, 12);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Maxime magnam impedit eos et rerum excepturi aut illum.", 57, 14);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Vel rem quam non excepturi.", 58, 6);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Rem accusantium odio laborum ea.", 58, 5);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Et voluptatem porro.", 59, 13);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Aut sed totam nostrum.", 59, 15);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Delectus autem fugit.", 60, 9);
INSERT INTO PostComment (comment_body, post_id, user_id) VALUES ("Minus non ipsa dolorem.", 60, 3);
